/*
 * autogenerated code by timezones.py
 */

#include <Arduino.h>

namespace data {

// timezone names
constexpr const char Africa_Abidjan[] PROGMEM = "Africa/Abidjan";
constexpr const char Africa_Accra[] PROGMEM = "Africa/Accra";
constexpr const char Africa_Addis_Ababa[] PROGMEM = "Africa/Addis_Ababa";
constexpr const char Africa_Algiers[] PROGMEM = "Africa/Algiers";
constexpr const char Africa_Asmara[] PROGMEM = "Africa/Asmara";
constexpr const char Africa_Bamako[] PROGMEM = "Africa/Bamako";
constexpr const char Africa_Bangui[] PROGMEM = "Africa/Bangui";
constexpr const char Africa_Banjul[] PROGMEM = "Africa/Banjul";
constexpr const char Africa_Bissau[] PROGMEM = "Africa/Bissau";
constexpr const char Africa_Blantyre[] PROGMEM = "Africa/Blantyre";
constexpr const char Africa_Brazzaville[] PROGMEM = "Africa/Brazzaville";
constexpr const char Africa_Bujumbura[] PROGMEM = "Africa/Bujumbura";
constexpr const char Africa_Cairo[] PROGMEM = "Africa/Cairo";
constexpr const char Africa_Casablanca[] PROGMEM = "Africa/Casablanca";
constexpr const char Africa_Ceuta[] PROGMEM = "Africa/Ceuta";
constexpr const char Africa_Conakry[] PROGMEM = "Africa/Conakry";
constexpr const char Africa_Dakar[] PROGMEM = "Africa/Dakar";
constexpr const char Africa_Dar_es_Salaam[] PROGMEM = "Africa/Dar_es_Salaam";
constexpr const char Africa_Djibouti[] PROGMEM = "Africa/Djibouti";
constexpr const char Africa_Douala[] PROGMEM = "Africa/Douala";
constexpr const char Africa_El_Aaiun[] PROGMEM = "Africa/El_Aaiun";
constexpr const char Africa_Freetown[] PROGMEM = "Africa/Freetown";
constexpr const char Africa_Gaborone[] PROGMEM = "Africa/Gaborone";
constexpr const char Africa_Harare[] PROGMEM = "Africa/Harare";
constexpr const char Africa_Johannesburg[] PROGMEM = "Africa/Johannesburg";
constexpr const char Africa_Juba[] PROGMEM = "Africa/Juba";
constexpr const char Africa_Kampala[] PROGMEM = "Africa/Kampala";
constexpr const char Africa_Khartoum[] PROGMEM = "Africa/Khartoum";
constexpr const char Africa_Kigali[] PROGMEM = "Africa/Kigali";
constexpr const char Africa_Kinshasa[] PROGMEM = "Africa/Kinshasa";
constexpr const char Africa_Lagos[] PROGMEM = "Africa/Lagos";
constexpr const char Africa_Libreville[] PROGMEM = "Africa/Libreville";
constexpr const char Africa_Lome[] PROGMEM = "Africa/Lome";
constexpr const char Africa_Luanda[] PROGMEM = "Africa/Luanda";
constexpr const char Africa_Lubumbashi[] PROGMEM = "Africa/Lubumbashi";
constexpr const char Africa_Lusaka[] PROGMEM = "Africa/Lusaka";
constexpr const char Africa_Malabo[] PROGMEM = "Africa/Malabo";
constexpr const char Africa_Maputo[] PROGMEM = "Africa/Maputo";
constexpr const char Africa_Maseru[] PROGMEM = "Africa/Maseru";
constexpr const char Africa_Mbabane[] PROGMEM = "Africa/Mbabane";
constexpr const char Africa_Mogadishu[] PROGMEM = "Africa/Mogadishu";
constexpr const char Africa_Monrovia[] PROGMEM = "Africa/Monrovia";
constexpr const char Africa_Nairobi[] PROGMEM = "Africa/Nairobi";
constexpr const char Africa_Ndjamena[] PROGMEM = "Africa/Ndjamena";
constexpr const char Africa_Niamey[] PROGMEM = "Africa/Niamey";
constexpr const char Africa_Nouakchott[] PROGMEM = "Africa/Nouakchott";
constexpr const char Africa_Ouagadougou[] PROGMEM = "Africa/Ouagadougou";
constexpr const char Africa_Porto_Novo[] PROGMEM = "Africa/Porto-Novo";
constexpr const char Africa_Sao_Tome[] PROGMEM = "Africa/Sao_Tome";
constexpr const char Africa_Tripoli[] PROGMEM = "Africa/Tripoli";
constexpr const char Africa_Tunis[] PROGMEM = "Africa/Tunis";
constexpr const char Africa_Windhoek[] PROGMEM = "Africa/Windhoek";
constexpr const char America_Adak[] PROGMEM = "America/Adak";
constexpr const char America_Anchorage[] PROGMEM = "America/Anchorage";
constexpr const char America_Anguilla[] PROGMEM = "America/Anguilla";
constexpr const char America_Antigua[] PROGMEM = "America/Antigua";
constexpr const char America_Araguaina[] PROGMEM = "America/Araguaina";
constexpr const char America_Argentina_Buenos_Aires[] PROGMEM = "America/Argentina/Buenos_Aires";
constexpr const char America_Argentina_Catamarca[] PROGMEM = "America/Argentina/Catamarca";
constexpr const char America_Argentina_Cordoba[] PROGMEM = "America/Argentina/Cordoba";
constexpr const char America_Argentina_Jujuy[] PROGMEM = "America/Argentina/Jujuy";
constexpr const char America_Argentina_La_Rioja[] PROGMEM = "America/Argentina/La_Rioja";
constexpr const char America_Argentina_Mendoza[] PROGMEM = "America/Argentina/Mendoza";
constexpr const char America_Argentina_Rio_Gallegos[] PROGMEM = "America/Argentina/Rio_Gallegos";
constexpr const char America_Argentina_Salta[] PROGMEM = "America/Argentina/Salta";
constexpr const char America_Argentina_San_Juan[] PROGMEM = "America/Argentina/San_Juan";
constexpr const char America_Argentina_San_Luis[] PROGMEM = "America/Argentina/San_Luis";
constexpr const char America_Argentina_Tucuman[] PROGMEM = "America/Argentina/Tucuman";
constexpr const char America_Argentina_Ushuaia[] PROGMEM = "America/Argentina/Ushuaia";
constexpr const char America_Aruba[] PROGMEM = "America/Aruba";
constexpr const char America_Asuncion[] PROGMEM = "America/Asuncion";
constexpr const char America_Atikokan[] PROGMEM = "America/Atikokan";
constexpr const char America_Bahia[] PROGMEM = "America/Bahia";
constexpr const char America_Bahia_Banderas[] PROGMEM = "America/Bahia_Banderas";
constexpr const char America_Barbados[] PROGMEM = "America/Barbados";
constexpr const char America_Belem[] PROGMEM = "America/Belem";
constexpr const char America_Belize[] PROGMEM = "America/Belize";
constexpr const char America_Blanc_Sablon[] PROGMEM = "America/Blanc-Sablon";
constexpr const char America_Boa_Vista[] PROGMEM = "America/Boa_Vista";
constexpr const char America_Bogota[] PROGMEM = "America/Bogota";
constexpr const char America_Boise[] PROGMEM = "America/Boise";
constexpr const char America_Cambridge_Bay[] PROGMEM = "America/Cambridge_Bay";
constexpr const char America_Campo_Grande[] PROGMEM = "America/Campo_Grande";
constexpr const char America_Cancun[] PROGMEM = "America/Cancun";
constexpr const char America_Caracas[] PROGMEM = "America/Caracas";
constexpr const char America_Cayenne[] PROGMEM = "America/Cayenne";
constexpr const char America_Cayman[] PROGMEM = "America/Cayman";
constexpr const char America_Chicago[] PROGMEM = "America/Chicago";
constexpr const char America_Chihuahua[] PROGMEM = "America/Chihuahua";
constexpr const char America_Costa_Rica[] PROGMEM = "America/Costa_Rica";
constexpr const char America_Creston[] PROGMEM = "America/Creston";
constexpr const char America_Cuiaba[] PROGMEM = "America/Cuiaba";
constexpr const char America_Curacao[] PROGMEM = "America/Curacao";
constexpr const char America_Danmarkshavn[] PROGMEM = "America/Danmarkshavn";
constexpr const char America_Dawson[] PROGMEM = "America/Dawson";
constexpr const char America_Dawson_Creek[] PROGMEM = "America/Dawson_Creek";
constexpr const char America_Denver[] PROGMEM = "America/Denver";
constexpr const char America_Detroit[] PROGMEM = "America/Detroit";
constexpr const char America_Dominica[] PROGMEM = "America/Dominica";
constexpr const char America_Edmonton[] PROGMEM = "America/Edmonton";
constexpr const char America_Eirunepe[] PROGMEM = "America/Eirunepe";
constexpr const char America_El_Salvador[] PROGMEM = "America/El_Salvador";
constexpr const char America_Fortaleza[] PROGMEM = "America/Fortaleza";
constexpr const char America_Fort_Nelson[] PROGMEM = "America/Fort_Nelson";
constexpr const char America_Glace_Bay[] PROGMEM = "America/Glace_Bay";
constexpr const char America_Godthab[] PROGMEM = "America/Godthab";
constexpr const char America_Goose_Bay[] PROGMEM = "America/Goose_Bay";
constexpr const char America_Grand_Turk[] PROGMEM = "America/Grand_Turk";
constexpr const char America_Grenada[] PROGMEM = "America/Grenada";
constexpr const char America_Guadeloupe[] PROGMEM = "America/Guadeloupe";
constexpr const char America_Guatemala[] PROGMEM = "America/Guatemala";
constexpr const char America_Guayaquil[] PROGMEM = "America/Guayaquil";
constexpr const char America_Guyana[] PROGMEM = "America/Guyana";
constexpr const char America_Halifax[] PROGMEM = "America/Halifax";
constexpr const char America_Havana[] PROGMEM = "America/Havana";
constexpr const char America_Hermosillo[] PROGMEM = "America/Hermosillo";
constexpr const char America_Indiana_Indianapolis[] PROGMEM = "America/Indiana/Indianapolis";
constexpr const char America_Indiana_Knox[] PROGMEM = "America/Indiana/Knox";
constexpr const char America_Indiana_Marengo[] PROGMEM = "America/Indiana/Marengo";
constexpr const char America_Indiana_Petersburg[] PROGMEM = "America/Indiana/Petersburg";
constexpr const char America_Indiana_Tell_City[] PROGMEM = "America/Indiana/Tell_City";
constexpr const char America_Indiana_Vevay[] PROGMEM = "America/Indiana/Vevay";
constexpr const char America_Indiana_Vincennes[] PROGMEM = "America/Indiana/Vincennes";
constexpr const char America_Indiana_Winamac[] PROGMEM = "America/Indiana/Winamac";
constexpr const char America_Inuvik[] PROGMEM = "America/Inuvik";
constexpr const char America_Iqaluit[] PROGMEM = "America/Iqaluit";
constexpr const char America_Jamaica[] PROGMEM = "America/Jamaica";
constexpr const char America_Juneau[] PROGMEM = "America/Juneau";
constexpr const char America_Kentucky_Louisville[] PROGMEM = "America/Kentucky/Louisville";
constexpr const char America_Kentucky_Monticello[] PROGMEM = "America/Kentucky/Monticello";
constexpr const char America_Kralendijk[] PROGMEM = "America/Kralendijk";
constexpr const char America_La_Paz[] PROGMEM = "America/La_Paz";
constexpr const char America_Lima[] PROGMEM = "America/Lima";
constexpr const char America_Los_Angeles[] PROGMEM = "America/Los_Angeles";
constexpr const char America_Lower_Princes[] PROGMEM = "America/Lower_Princes";
constexpr const char America_Maceio[] PROGMEM = "America/Maceio";
constexpr const char America_Managua[] PROGMEM = "America/Managua";
constexpr const char America_Manaus[] PROGMEM = "America/Manaus";
constexpr const char America_Marigot[] PROGMEM = "America/Marigot";
constexpr const char America_Martinique[] PROGMEM = "America/Martinique";
constexpr const char America_Matamoros[] PROGMEM = "America/Matamoros";
constexpr const char America_Mazatlan[] PROGMEM = "America/Mazatlan";
constexpr const char America_Menominee[] PROGMEM = "America/Menominee";
constexpr const char America_Merida[] PROGMEM = "America/Merida";
constexpr const char America_Metlakatla[] PROGMEM = "America/Metlakatla";
constexpr const char America_Mexico_City[] PROGMEM = "America/Mexico_City";
constexpr const char America_Miquelon[] PROGMEM = "America/Miquelon";
constexpr const char America_Moncton[] PROGMEM = "America/Moncton";
constexpr const char America_Monterrey[] PROGMEM = "America/Monterrey";
constexpr const char America_Montevideo[] PROGMEM = "America/Montevideo";
constexpr const char America_Montreal[] PROGMEM = "America/Montreal";
constexpr const char America_Montserrat[] PROGMEM = "America/Montserrat";
constexpr const char America_Nassau[] PROGMEM = "America/Nassau";
constexpr const char America_New_York[] PROGMEM = "America/New_York";
constexpr const char America_Nipigon[] PROGMEM = "America/Nipigon";
constexpr const char America_Nome[] PROGMEM = "America/Nome";
constexpr const char America_Noronha[] PROGMEM = "America/Noronha";
constexpr const char America_North_Dakota_Beulah[] PROGMEM = "America/North_Dakota/Beulah";
constexpr const char America_North_Dakota_Center[] PROGMEM = "America/North_Dakota/Center";
constexpr const char America_North_Dakota_New_Salem[] PROGMEM = "America/North_Dakota/New_Salem";
constexpr const char America_Nuuk[] PROGMEM = "America/Nuuk";
constexpr const char America_Ojinaga[] PROGMEM = "America/Ojinaga";
constexpr const char America_Panama[] PROGMEM = "America/Panama";
constexpr const char America_Pangnirtung[] PROGMEM = "America/Pangnirtung";
constexpr const char America_Paramaribo[] PROGMEM = "America/Paramaribo";
constexpr const char America_Phoenix[] PROGMEM = "America/Phoenix";
constexpr const char America_Port_au_Prince[] PROGMEM = "America/Port-au-Prince";
constexpr const char America_Port_of_Spain[] PROGMEM = "America/Port_of_Spain";
constexpr const char America_Porto_Velho[] PROGMEM = "America/Porto_Velho";
constexpr const char America_Puerto_Rico[] PROGMEM = "America/Puerto_Rico";
constexpr const char America_Punta_Arenas[] PROGMEM = "America/Punta_Arenas";
constexpr const char America_Rainy_River[] PROGMEM = "America/Rainy_River";
constexpr const char America_Rankin_Inlet[] PROGMEM = "America/Rankin_Inlet";
constexpr const char America_Recife[] PROGMEM = "America/Recife";
constexpr const char America_Regina[] PROGMEM = "America/Regina";
constexpr const char America_Resolute[] PROGMEM = "America/Resolute";
constexpr const char America_Rio_Branco[] PROGMEM = "America/Rio_Branco";
constexpr const char America_Santarem[] PROGMEM = "America/Santarem";
constexpr const char America_Santiago[] PROGMEM = "America/Santiago";
constexpr const char America_Santo_Domingo[] PROGMEM = "America/Santo_Domingo";
constexpr const char America_Sao_Paulo[] PROGMEM = "America/Sao_Paulo";
constexpr const char America_Scoresbysund[] PROGMEM = "America/Scoresbysund";
constexpr const char America_Sitka[] PROGMEM = "America/Sitka";
constexpr const char America_St_Barthelemy[] PROGMEM = "America/St_Barthelemy";
constexpr const char America_St_Johns[] PROGMEM = "America/St_Johns";
constexpr const char America_St_Kitts[] PROGMEM = "America/St_Kitts";
constexpr const char America_St_Lucia[] PROGMEM = "America/St_Lucia";
constexpr const char America_St_Thomas[] PROGMEM = "America/St_Thomas";
constexpr const char America_St_Vincent[] PROGMEM = "America/St_Vincent";
constexpr const char America_Swift_Current[] PROGMEM = "America/Swift_Current";
constexpr const char America_Tegucigalpa[] PROGMEM = "America/Tegucigalpa";
constexpr const char America_Thule[] PROGMEM = "America/Thule";
constexpr const char America_Thunder_Bay[] PROGMEM = "America/Thunder_Bay";
constexpr const char America_Tijuana[] PROGMEM = "America/Tijuana";
constexpr const char America_Toronto[] PROGMEM = "America/Toronto";
constexpr const char America_Tortola[] PROGMEM = "America/Tortola";
constexpr const char America_Vancouver[] PROGMEM = "America/Vancouver";
constexpr const char America_Whitehorse[] PROGMEM = "America/Whitehorse";
constexpr const char America_Winnipeg[] PROGMEM = "America/Winnipeg";
constexpr const char America_Yakutat[] PROGMEM = "America/Yakutat";
constexpr const char America_Yellowknife[] PROGMEM = "America/Yellowknife";
constexpr const char Antarctica_Casey[] PROGMEM = "Antarctica/Casey";
constexpr const char Antarctica_Davis[] PROGMEM = "Antarctica/Davis";
constexpr const char Antarctica_DumontDUrville[] PROGMEM = "Antarctica/DumontDUrville";
constexpr const char Antarctica_Macquarie[] PROGMEM = "Antarctica/Macquarie";
constexpr const char Antarctica_Mawson[] PROGMEM = "Antarctica/Mawson";
constexpr const char Antarctica_McMurdo[] PROGMEM = "Antarctica/McMurdo";
constexpr const char Antarctica_Palmer[] PROGMEM = "Antarctica/Palmer";
constexpr const char Antarctica_Rothera[] PROGMEM = "Antarctica/Rothera";
constexpr const char Antarctica_Syowa[] PROGMEM = "Antarctica/Syowa";
constexpr const char Antarctica_Troll[] PROGMEM = "Antarctica/Troll";
constexpr const char Antarctica_Vostok[] PROGMEM = "Antarctica/Vostok";
constexpr const char Arctic_Longyearbyen[] PROGMEM = "Arctic/Longyearbyen";
constexpr const char Asia_Aden[] PROGMEM = "Asia/Aden";
constexpr const char Asia_Almaty[] PROGMEM = "Asia/Almaty";
constexpr const char Asia_Amman[] PROGMEM = "Asia/Amman";
constexpr const char Asia_Anadyr[] PROGMEM = "Asia/Anadyr";
constexpr const char Asia_Aqtau[] PROGMEM = "Asia/Aqtau";
constexpr const char Asia_Aqtobe[] PROGMEM = "Asia/Aqtobe";
constexpr const char Asia_Ashgabat[] PROGMEM = "Asia/Ashgabat";
constexpr const char Asia_Atyrau[] PROGMEM = "Asia/Atyrau";
constexpr const char Asia_Baghdad[] PROGMEM = "Asia/Baghdad";
constexpr const char Asia_Bahrain[] PROGMEM = "Asia/Bahrain";
constexpr const char Asia_Baku[] PROGMEM = "Asia/Baku";
constexpr const char Asia_Bangkok[] PROGMEM = "Asia/Bangkok";
constexpr const char Asia_Barnaul[] PROGMEM = "Asia/Barnaul";
constexpr const char Asia_Beirut[] PROGMEM = "Asia/Beirut";
constexpr const char Asia_Bishkek[] PROGMEM = "Asia/Bishkek";
constexpr const char Asia_Brunei[] PROGMEM = "Asia/Brunei";
constexpr const char Asia_Chita[] PROGMEM = "Asia/Chita";
constexpr const char Asia_Choibalsan[] PROGMEM = "Asia/Choibalsan";
constexpr const char Asia_Colombo[] PROGMEM = "Asia/Colombo";
constexpr const char Asia_Damascus[] PROGMEM = "Asia/Damascus";
constexpr const char Asia_Dhaka[] PROGMEM = "Asia/Dhaka";
constexpr const char Asia_Dili[] PROGMEM = "Asia/Dili";
constexpr const char Asia_Dubai[] PROGMEM = "Asia/Dubai";
constexpr const char Asia_Dushanbe[] PROGMEM = "Asia/Dushanbe";
constexpr const char Asia_Famagusta[] PROGMEM = "Asia/Famagusta";
constexpr const char Asia_Gaza[] PROGMEM = "Asia/Gaza";
constexpr const char Asia_Hebron[] PROGMEM = "Asia/Hebron";
constexpr const char Asia_Ho_Chi_Minh[] PROGMEM = "Asia/Ho_Chi_Minh";
constexpr const char Asia_Hong_Kong[] PROGMEM = "Asia/Hong_Kong";
constexpr const char Asia_Hovd[] PROGMEM = "Asia/Hovd";
constexpr const char Asia_Irkutsk[] PROGMEM = "Asia/Irkutsk";
constexpr const char Asia_Jakarta[] PROGMEM = "Asia/Jakarta";
constexpr const char Asia_Jayapura[] PROGMEM = "Asia/Jayapura";
constexpr const char Asia_Jerusalem[] PROGMEM = "Asia/Jerusalem";
constexpr const char Asia_Kabul[] PROGMEM = "Asia/Kabul";
constexpr const char Asia_Kamchatka[] PROGMEM = "Asia/Kamchatka";
constexpr const char Asia_Karachi[] PROGMEM = "Asia/Karachi";
constexpr const char Asia_Kathmandu[] PROGMEM = "Asia/Kathmandu";
constexpr const char Asia_Khandyga[] PROGMEM = "Asia/Khandyga";
constexpr const char Asia_Kolkata[] PROGMEM = "Asia/Kolkata";
constexpr const char Asia_Krasnoyarsk[] PROGMEM = "Asia/Krasnoyarsk";
constexpr const char Asia_Kuala_Lumpur[] PROGMEM = "Asia/Kuala_Lumpur";
constexpr const char Asia_Kuching[] PROGMEM = "Asia/Kuching";
constexpr const char Asia_Kuwait[] PROGMEM = "Asia/Kuwait";
constexpr const char Asia_Macau[] PROGMEM = "Asia/Macau";
constexpr const char Asia_Magadan[] PROGMEM = "Asia/Magadan";
constexpr const char Asia_Makassar[] PROGMEM = "Asia/Makassar";
constexpr const char Asia_Manila[] PROGMEM = "Asia/Manila";
constexpr const char Asia_Muscat[] PROGMEM = "Asia/Muscat";
constexpr const char Asia_Nicosia[] PROGMEM = "Asia/Nicosia";
constexpr const char Asia_Novokuznetsk[] PROGMEM = "Asia/Novokuznetsk";
constexpr const char Asia_Novosibirsk[] PROGMEM = "Asia/Novosibirsk";
constexpr const char Asia_Omsk[] PROGMEM = "Asia/Omsk";
constexpr const char Asia_Oral[] PROGMEM = "Asia/Oral";
constexpr const char Asia_Phnom_Penh[] PROGMEM = "Asia/Phnom_Penh";
constexpr const char Asia_Pontianak[] PROGMEM = "Asia/Pontianak";
constexpr const char Asia_Pyongyang[] PROGMEM = "Asia/Pyongyang";
constexpr const char Asia_Qatar[] PROGMEM = "Asia/Qatar";
constexpr const char Asia_Qyzylorda[] PROGMEM = "Asia/Qyzylorda";
constexpr const char Asia_Riyadh[] PROGMEM = "Asia/Riyadh";
constexpr const char Asia_Sakhalin[] PROGMEM = "Asia/Sakhalin";
constexpr const char Asia_Samarkand[] PROGMEM = "Asia/Samarkand";
constexpr const char Asia_Seoul[] PROGMEM = "Asia/Seoul";
constexpr const char Asia_Shanghai[] PROGMEM = "Asia/Shanghai";
constexpr const char Asia_Singapore[] PROGMEM = "Asia/Singapore";
constexpr const char Asia_Srednekolymsk[] PROGMEM = "Asia/Srednekolymsk";
constexpr const char Asia_Taipei[] PROGMEM = "Asia/Taipei";
constexpr const char Asia_Tashkent[] PROGMEM = "Asia/Tashkent";
constexpr const char Asia_Tbilisi[] PROGMEM = "Asia/Tbilisi";
constexpr const char Asia_Tehran[] PROGMEM = "Asia/Tehran";
constexpr const char Asia_Thimphu[] PROGMEM = "Asia/Thimphu";
constexpr const char Asia_Tokyo[] PROGMEM = "Asia/Tokyo";
constexpr const char Asia_Tomsk[] PROGMEM = "Asia/Tomsk";
constexpr const char Asia_Ulaanbaatar[] PROGMEM = "Asia/Ulaanbaatar";
constexpr const char Asia_Urumqi[] PROGMEM = "Asia/Urumqi";
constexpr const char Asia_Ust_Nera[] PROGMEM = "Asia/Ust-Nera";
constexpr const char Asia_Vientiane[] PROGMEM = "Asia/Vientiane";
constexpr const char Asia_Vladivostok[] PROGMEM = "Asia/Vladivostok";
constexpr const char Asia_Yakutsk[] PROGMEM = "Asia/Yakutsk";
constexpr const char Asia_Yangon[] PROGMEM = "Asia/Yangon";
constexpr const char Asia_Yekaterinburg[] PROGMEM = "Asia/Yekaterinburg";
constexpr const char Asia_Yerevan[] PROGMEM = "Asia/Yerevan";
constexpr const char Atlantic_Azores[] PROGMEM = "Atlantic/Azores";
constexpr const char Atlantic_Bermuda[] PROGMEM = "Atlantic/Bermuda";
constexpr const char Atlantic_Canary[] PROGMEM = "Atlantic/Canary";
constexpr const char Atlantic_Cape_Verde[] PROGMEM = "Atlantic/Cape_Verde";
constexpr const char Atlantic_Faroe[] PROGMEM = "Atlantic/Faroe";
constexpr const char Atlantic_Madeira[] PROGMEM = "Atlantic/Madeira";
constexpr const char Atlantic_Reykjavik[] PROGMEM = "Atlantic/Reykjavik";
constexpr const char Atlantic_South_Georgia[] PROGMEM = "Atlantic/South_Georgia";
constexpr const char Atlantic_Stanley[] PROGMEM = "Atlantic/Stanley";
constexpr const char Atlantic_St_Helena[] PROGMEM = "Atlantic/St_Helena";
constexpr const char Australia_Adelaide[] PROGMEM = "Australia/Adelaide";
constexpr const char Australia_Brisbane[] PROGMEM = "Australia/Brisbane";
constexpr const char Australia_Broken_Hill[] PROGMEM = "Australia/Broken_Hill";
constexpr const char Australia_Currie[] PROGMEM = "Australia/Currie";
constexpr const char Australia_Darwin[] PROGMEM = "Australia/Darwin";
constexpr const char Australia_Eucla[] PROGMEM = "Australia/Eucla";
constexpr const char Australia_Hobart[] PROGMEM = "Australia/Hobart";
constexpr const char Australia_Lindeman[] PROGMEM = "Australia/Lindeman";
constexpr const char Australia_Lord_Howe[] PROGMEM = "Australia/Lord_Howe";
constexpr const char Australia_Melbourne[] PROGMEM = "Australia/Melbourne";
constexpr const char Australia_Perth[] PROGMEM = "Australia/Perth";
constexpr const char Australia_Sydney[] PROGMEM = "Australia/Sydney";
constexpr const char Europe_Amsterdam[] PROGMEM = "Europe/Amsterdam";
constexpr const char Europe_Andorra[] PROGMEM = "Europe/Andorra";
constexpr const char Europe_Astrakhan[] PROGMEM = "Europe/Astrakhan";
constexpr const char Europe_Athens[] PROGMEM = "Europe/Athens";
constexpr const char Europe_Belgrade[] PROGMEM = "Europe/Belgrade";
constexpr const char Europe_Berlin[] PROGMEM = "Europe/Berlin";
constexpr const char Europe_Bratislava[] PROGMEM = "Europe/Bratislava";
constexpr const char Europe_Brussels[] PROGMEM = "Europe/Brussels";
constexpr const char Europe_Bucharest[] PROGMEM = "Europe/Bucharest";
constexpr const char Europe_Budapest[] PROGMEM = "Europe/Budapest";
constexpr const char Europe_Busingen[] PROGMEM = "Europe/Busingen";
constexpr const char Europe_Chisinau[] PROGMEM = "Europe/Chisinau";
constexpr const char Europe_Copenhagen[] PROGMEM = "Europe/Copenhagen";
constexpr const char Europe_Dublin[] PROGMEM = "Europe/Dublin";
constexpr const char Europe_Gibraltar[] PROGMEM = "Europe/Gibraltar";
constexpr const char Europe_Guernsey[] PROGMEM = "Europe/Guernsey";
constexpr const char Europe_Helsinki[] PROGMEM = "Europe/Helsinki";
constexpr const char Europe_Isle_of_Man[] PROGMEM = "Europe/Isle_of_Man";
constexpr const char Europe_Istanbul[] PROGMEM = "Europe/Istanbul";
constexpr const char Europe_Jersey[] PROGMEM = "Europe/Jersey";
constexpr const char Europe_Kaliningrad[] PROGMEM = "Europe/Kaliningrad";
constexpr const char Europe_Kiev[] PROGMEM = "Europe/Kiev";
constexpr const char Europe_Kirov[] PROGMEM = "Europe/Kirov";
constexpr const char Europe_Lisbon[] PROGMEM = "Europe/Lisbon";
constexpr const char Europe_Ljubljana[] PROGMEM = "Europe/Ljubljana";
constexpr const char Europe_London[] PROGMEM = "Europe/London";
constexpr const char Europe_Luxembourg[] PROGMEM = "Europe/Luxembourg";
constexpr const char Europe_Madrid[] PROGMEM = "Europe/Madrid";
constexpr const char Europe_Malta[] PROGMEM = "Europe/Malta";
constexpr const char Europe_Mariehamn[] PROGMEM = "Europe/Mariehamn";
constexpr const char Europe_Minsk[] PROGMEM = "Europe/Minsk";
constexpr const char Europe_Monaco[] PROGMEM = "Europe/Monaco";
constexpr const char Europe_Moscow[] PROGMEM = "Europe/Moscow";
constexpr const char Europe_Oslo[] PROGMEM = "Europe/Oslo";
constexpr const char Europe_Paris[] PROGMEM = "Europe/Paris";
constexpr const char Europe_Podgorica[] PROGMEM = "Europe/Podgorica";
constexpr const char Europe_Prague[] PROGMEM = "Europe/Prague";
constexpr const char Europe_Riga[] PROGMEM = "Europe/Riga";
constexpr const char Europe_Rome[] PROGMEM = "Europe/Rome";
constexpr const char Europe_Samara[] PROGMEM = "Europe/Samara";
constexpr const char Europe_San_Marino[] PROGMEM = "Europe/San_Marino";
constexpr const char Europe_Sarajevo[] PROGMEM = "Europe/Sarajevo";
constexpr const char Europe_Saratov[] PROGMEM = "Europe/Saratov";
constexpr const char Europe_Simferopol[] PROGMEM = "Europe/Simferopol";
constexpr const char Europe_Skopje[] PROGMEM = "Europe/Skopje";
constexpr const char Europe_Sofia[] PROGMEM = "Europe/Sofia";
constexpr const char Europe_Stockholm[] PROGMEM = "Europe/Stockholm";
constexpr const char Europe_Tallinn[] PROGMEM = "Europe/Tallinn";
constexpr const char Europe_Tirane[] PROGMEM = "Europe/Tirane";
constexpr const char Europe_Ulyanovsk[] PROGMEM = "Europe/Ulyanovsk";
constexpr const char Europe_Uzhgorod[] PROGMEM = "Europe/Uzhgorod";
constexpr const char Europe_Vaduz[] PROGMEM = "Europe/Vaduz";
constexpr const char Europe_Vatican[] PROGMEM = "Europe/Vatican";
constexpr const char Europe_Vienna[] PROGMEM = "Europe/Vienna";
constexpr const char Europe_Vilnius[] PROGMEM = "Europe/Vilnius";
constexpr const char Europe_Volgograd[] PROGMEM = "Europe/Volgograd";
constexpr const char Europe_Warsaw[] PROGMEM = "Europe/Warsaw";
constexpr const char Europe_Zagreb[] PROGMEM = "Europe/Zagreb";
constexpr const char Europe_Zaporozhye[] PROGMEM = "Europe/Zaporozhye";
constexpr const char Europe_Zurich[] PROGMEM = "Europe/Zurich";
constexpr const char Indian_Antananarivo[] PROGMEM = "Indian/Antananarivo";
constexpr const char Indian_Chagos[] PROGMEM = "Indian/Chagos";
constexpr const char Indian_Christmas[] PROGMEM = "Indian/Christmas";
constexpr const char Indian_Cocos[] PROGMEM = "Indian/Cocos";
constexpr const char Indian_Comoro[] PROGMEM = "Indian/Comoro";
constexpr const char Indian_Kerguelen[] PROGMEM = "Indian/Kerguelen";
constexpr const char Indian_Mahe[] PROGMEM = "Indian/Mahe";
constexpr const char Indian_Maldives[] PROGMEM = "Indian/Maldives";
constexpr const char Indian_Mauritius[] PROGMEM = "Indian/Mauritius";
constexpr const char Indian_Mayotte[] PROGMEM = "Indian/Mayotte";
constexpr const char Indian_Reunion[] PROGMEM = "Indian/Reunion";
constexpr const char Pacific_Apia[] PROGMEM = "Pacific/Apia";
constexpr const char Pacific_Auckland[] PROGMEM = "Pacific/Auckland";
constexpr const char Pacific_Bougainville[] PROGMEM = "Pacific/Bougainville";
constexpr const char Pacific_Chatham[] PROGMEM = "Pacific/Chatham";
constexpr const char Pacific_Chuuk[] PROGMEM = "Pacific/Chuuk";
constexpr const char Pacific_Easter[] PROGMEM = "Pacific/Easter";
constexpr const char Pacific_Efate[] PROGMEM = "Pacific/Efate";
constexpr const char Pacific_Enderbury[] PROGMEM = "Pacific/Enderbury";
constexpr const char Pacific_Fakaofo[] PROGMEM = "Pacific/Fakaofo";
constexpr const char Pacific_Fiji[] PROGMEM = "Pacific/Fiji";
constexpr const char Pacific_Funafuti[] PROGMEM = "Pacific/Funafuti";
constexpr const char Pacific_Galapagos[] PROGMEM = "Pacific/Galapagos";
constexpr const char Pacific_Gambier[] PROGMEM = "Pacific/Gambier";
constexpr const char Pacific_Guadalcanal[] PROGMEM = "Pacific/Guadalcanal";
constexpr const char Pacific_Guam[] PROGMEM = "Pacific/Guam";
constexpr const char Pacific_Honolulu[] PROGMEM = "Pacific/Honolulu";
constexpr const char Pacific_Kiritimati[] PROGMEM = "Pacific/Kiritimati";
constexpr const char Pacific_Kosrae[] PROGMEM = "Pacific/Kosrae";
constexpr const char Pacific_Kwajalein[] PROGMEM = "Pacific/Kwajalein";
constexpr const char Pacific_Majuro[] PROGMEM = "Pacific/Majuro";
constexpr const char Pacific_Marquesas[] PROGMEM = "Pacific/Marquesas";
constexpr const char Pacific_Midway[] PROGMEM = "Pacific/Midway";
constexpr const char Pacific_Nauru[] PROGMEM = "Pacific/Nauru";
constexpr const char Pacific_Niue[] PROGMEM = "Pacific/Niue";
constexpr const char Pacific_Norfolk[] PROGMEM = "Pacific/Norfolk";
constexpr const char Pacific_Noumea[] PROGMEM = "Pacific/Noumea";
constexpr const char Pacific_Pago_Pago[] PROGMEM = "Pacific/Pago_Pago";
constexpr const char Pacific_Palau[] PROGMEM = "Pacific/Palau";
constexpr const char Pacific_Pitcairn[] PROGMEM = "Pacific/Pitcairn";
constexpr const char Pacific_Pohnpei[] PROGMEM = "Pacific/Pohnpei";
constexpr const char Pacific_Port_Moresby[] PROGMEM = "Pacific/Port_Moresby";
constexpr const char Pacific_Rarotonga[] PROGMEM = "Pacific/Rarotonga";
constexpr const char Pacific_Saipan[] PROGMEM = "Pacific/Saipan";
constexpr const char Pacific_Tahiti[] PROGMEM = "Pacific/Tahiti";
constexpr const char Pacific_Tarawa[] PROGMEM = "Pacific/Tarawa";
constexpr const char Pacific_Tongatapu[] PROGMEM = "Pacific/Tongatapu";
constexpr const char Pacific_Wake[] PROGMEM = "Pacific/Wake";
constexpr const char Pacific_Wallis[] PROGMEM = "Pacific/Wallis";
constexpr const char Etc_GMT[] PROGMEM = "Etc/GMT";
constexpr const char Etc_GMT_0[] PROGMEM = "Etc/GMT+0";
constexpr const char Etc_GMT_1[] PROGMEM = "Etc/GMT+1";
constexpr const char Etc_GMT_2[] PROGMEM = "Etc/GMT+2";
constexpr const char Etc_GMT_3[] PROGMEM = "Etc/GMT+3";
constexpr const char Etc_GMT_4[] PROGMEM = "Etc/GMT+4";
constexpr const char Etc_GMT_5[] PROGMEM = "Etc/GMT+5";
constexpr const char Etc_GMT_6[] PROGMEM = "Etc/GMT+6";
constexpr const char Etc_GMT_7[] PROGMEM = "Etc/GMT+7";
constexpr const char Etc_GMT_8[] PROGMEM = "Etc/GMT+8";
constexpr const char Etc_GMT_9[] PROGMEM = "Etc/GMT+9";
constexpr const char Etc_GMT_10[] PROGMEM = "Etc/GMT+10";
constexpr const char Etc_GMT_11[] PROGMEM = "Etc/GMT+11";
constexpr const char Etc_GMT_12[] PROGMEM = "Etc/GMT+12";
constexpr const char Etc_GMT_13[] PROGMEM = "Etc/GMT-13";
constexpr const char Etc_GMT_14[] PROGMEM = "Etc/GMT-14";
constexpr const char Etc_GMT0[] PROGMEM = "Etc/GMT0";
constexpr const char Etc_UCT[] PROGMEM = "Etc/UCT";
constexpr const char Etc_UTC[] PROGMEM = "Etc/UTC";
constexpr const char Etc_Greenwich[] PROGMEM = "Etc/Greenwich";
constexpr const char Etc_Universal[] PROGMEM = "Etc/Universal";
constexpr const char Etc_Zulu[] PROGMEM = "Etc/Zulu";


// timezone codes
constexpr const char GMT0[] PROGMEM = "GMT0";
constexpr const char EATm3[] PROGMEM = "EAT-3";
constexpr const char CETm1[] PROGMEM = "CET-1";
constexpr const char WATm1[] PROGMEM = "WAT-1";
constexpr const char CATm2[] PROGMEM = "CAT-2";
constexpr const char EETm2[] PROGMEM = "EET-2";
constexpr const char _p01_m1[] PROGMEM = "<+01>-1";
constexpr const char CETm1CEST_M3_5_0_M10_5_0_3[] PROGMEM = "CET-1CEST,M3.5.0,M10.5.0/3";
constexpr const char SASTm2[] PROGMEM = "SAST-2";
constexpr const char HST10HDT_M3_2_0_M11_1_0[] PROGMEM = "HST10HDT,M3.2.0,M11.1.0";
constexpr const char AKST9AKDT_M3_2_0_M11_1_0[] PROGMEM = "AKST9AKDT,M3.2.0,M11.1.0";
constexpr const char AST4[] PROGMEM = "AST4";
constexpr const char _m03_3[] PROGMEM = "<-03>3";
constexpr const char _m04_4_m03__M10_1_0_0_M3_4_0_0[] PROGMEM = "<-04>4<-03>,M10.1.0/0,M3.4.0/0";
constexpr const char EST5[] PROGMEM = "EST5";
constexpr const char CST6CDT_M4_1_0_M10_5_0[] PROGMEM = "CST6CDT,M4.1.0,M10.5.0";
constexpr const char CST6[] PROGMEM = "CST6";
constexpr const char _m04_4[] PROGMEM = "<-04>4";
constexpr const char _m05_5[] PROGMEM = "<-05>5";
constexpr const char MST7MDT_M3_2_0_M11_1_0[] PROGMEM = "MST7MDT,M3.2.0,M11.1.0";
constexpr const char CST6CDT_M3_2_0_M11_1_0[] PROGMEM = "CST6CDT,M3.2.0,M11.1.0";
constexpr const char MST7MDT_M4_1_0_M10_5_0[] PROGMEM = "MST7MDT,M4.1.0,M10.5.0";
constexpr const char MST7[] PROGMEM = "MST7";
constexpr const char EST5EDT_M3_2_0_M11_1_0[] PROGMEM = "EST5EDT,M3.2.0,M11.1.0";
constexpr const char AST4ADT_M3_2_0_M11_1_0[] PROGMEM = "AST4ADT,M3.2.0,M11.1.0";
constexpr const char _m03_3_m02__M3_5_0_m2_M10_5_0_m1[] PROGMEM = "<-03>3<-02>,M3.5.0/-2,M10.5.0/-1";
constexpr const char CST5CDT_M3_2_0_0_M11_1_0_1[] PROGMEM = "CST5CDT,M3.2.0/0,M11.1.0/1";
constexpr const char PST8PDT_M3_2_0_M11_1_0[] PROGMEM = "PST8PDT,M3.2.0,M11.1.0";
constexpr const char _m03_3_m02__M3_2_0_M11_1_0[] PROGMEM = "<-03>3<-02>,M3.2.0,M11.1.0";
constexpr const char _m02_2[] PROGMEM = "<-02>2";
constexpr const char _m04_4_m03__M9_1_6_24_M4_1_6_24[] PROGMEM = "<-04>4<-03>,M9.1.6/24,M4.1.6/24";
constexpr const char _m01_1_p00__M3_5_0_0_M10_5_0_1[] PROGMEM = "<-01>1<+00>,M3.5.0/0,M10.5.0/1";
constexpr const char NST3_30NDT_M3_2_0_M11_1_0[] PROGMEM = "NST3:30NDT,M3.2.0,M11.1.0";
constexpr const char _p11_m11[] PROGMEM = "<+11>-11";
constexpr const char _p07_m7[] PROGMEM = "<+07>-7";
constexpr const char _p10_m10[] PROGMEM = "<+10>-10";
constexpr const char AESTm10AEDT_M10_1_0_M4_1_0_3[] PROGMEM = "AEST-10AEDT,M10.1.0,M4.1.0/3";
constexpr const char _p05_m5[] PROGMEM = "<+05>-5";
constexpr const char NZSTm12NZDT_M9_5_0_M4_1_0_3[] PROGMEM = "NZST-12NZDT,M9.5.0,M4.1.0/3";
constexpr const char _p03_m3[] PROGMEM = "<+03>-3";
constexpr const char _p00_0_p02_m2_M3_5_0_1_M10_5_0_3[] PROGMEM = "<+00>0<+02>-2,M3.5.0/1,M10.5.0/3";
constexpr const char _p06_m6[] PROGMEM = "<+06>-6";
constexpr const char EETm2EEST_M2_5_4_24_M10_5_5_1[] PROGMEM = "EET-2EEST,M2.5.4/24,M10.5.5/1";
constexpr const char _p12_m12[] PROGMEM = "<+12>-12";
constexpr const char _p04_m4[] PROGMEM = "<+04>-4";
constexpr const char EETm2EEST_M3_5_0_0_M10_5_0_0[] PROGMEM = "EET-2EEST,M3.5.0/0,M10.5.0/0";
constexpr const char _p08_m8[] PROGMEM = "<+08>-8";
constexpr const char _p09_m9[] PROGMEM = "<+09>-9";
constexpr const char _p0530_m5_30[] PROGMEM = "<+0530>-5:30";
constexpr const char EETm2EEST_M3_5_5_0_M10_5_5_0[] PROGMEM = "EET-2EEST,M3.5.5/0,M10.5.5/0";
constexpr const char EETm2EEST_M3_5_0_3_M10_5_0_4[] PROGMEM = "EET-2EEST,M3.5.0/3,M10.5.0/4";
constexpr const char EETm2EEST_M3_4_4_48_M10_5_5_1[] PROGMEM = "EET-2EEST,M3.4.4/48,M10.5.5/1";
constexpr const char HKTm8[] PROGMEM = "HKT-8";
constexpr const char WIBm7[] PROGMEM = "WIB-7";
constexpr const char WITm9[] PROGMEM = "WIT-9";
constexpr const char ISTm2IDT_M3_4_4_26_M10_5_0[] PROGMEM = "IST-2IDT,M3.4.4/26,M10.5.0";
constexpr const char _p0430_m4_30[] PROGMEM = "<+0430>-4:30";
constexpr const char PKTm5[] PROGMEM = "PKT-5";
constexpr const char _p0545_m5_45[] PROGMEM = "<+0545>-5:45";
constexpr const char ISTm5_30[] PROGMEM = "IST-5:30";
constexpr const char CSTm8[] PROGMEM = "CST-8";
constexpr const char WITAm8[] PROGMEM = "WITA-8";
constexpr const char PSTm8[] PROGMEM = "PST-8";
constexpr const char KSTm9[] PROGMEM = "KST-9";
constexpr const char _p0330_m3_30_p0430__J79_24_J263_24[] PROGMEM = "<+0330>-3:30<+0430>,J79/24,J263/24";
constexpr const char JSTm9[] PROGMEM = "JST-9";
constexpr const char _p0630_m6_30[] PROGMEM = "<+0630>-6:30";
constexpr const char WET0WEST_M3_5_0_1_M10_5_0[] PROGMEM = "WET0WEST,M3.5.0/1,M10.5.0";
constexpr const char _m01_1[] PROGMEM = "<-01>1";
constexpr const char ACSTm9_30ACDT_M10_1_0_M4_1_0_3[] PROGMEM = "ACST-9:30ACDT,M10.1.0,M4.1.0/3";
constexpr const char AESTm10[] PROGMEM = "AEST-10";
constexpr const char ACSTm9_30[] PROGMEM = "ACST-9:30";
constexpr const char _p0845_m8_45[] PROGMEM = "<+0845>-8:45";
constexpr const char _p1030_m10_30_p11_m11_M10_1_0_M4_1_0[] PROGMEM = "<+1030>-10:30<+11>-11,M10.1.0,M4.1.0";
constexpr const char AWSTm8[] PROGMEM = "AWST-8";
constexpr const char EETm2EEST_M3_5_0_M10_5_0_3[] PROGMEM = "EET-2EEST,M3.5.0,M10.5.0/3";
constexpr const char ISTm1GMT0_M10_5_0_M3_5_0_1[] PROGMEM = "IST-1GMT0,M10.5.0,M3.5.0/1";
constexpr const char GMT0BST_M3_5_0_1_M10_5_0[] PROGMEM = "GMT0BST,M3.5.0/1,M10.5.0";
constexpr const char MSKm3[] PROGMEM = "MSK-3";
constexpr const char _p13_m13[] PROGMEM = "<+13>-13";
constexpr const char _p1245_m12_45_p1345__M9_5_0_2_45_M4_1_0_3_45[] PROGMEM = "<+1245>-12:45<+1345>,M9.5.0/2:45,M4.1.0/3:45";
constexpr const char _m06_6_m05__M9_1_6_22_M4_1_6_22[] PROGMEM = "<-06>6<-05>,M9.1.6/22,M4.1.6/22";
constexpr const char _p12_m12_p13__M11_2_0_M1_2_3_99[] PROGMEM = "<+12>-12<+13>,M11.2.0,M1.2.3/99";
constexpr const char _m06_6[] PROGMEM = "<-06>6";
constexpr const char _m09_9[] PROGMEM = "<-09>9";
constexpr const char ChSTm10[] PROGMEM = "ChST-10";
constexpr const char HST10[] PROGMEM = "HST10";
constexpr const char _p14_m14[] PROGMEM = "<+14>-14";
constexpr const char _m0930_9_30[] PROGMEM = "<-0930>9:30";
constexpr const char SST11[] PROGMEM = "SST11";
constexpr const char _m11_11[] PROGMEM = "<-11>11";
constexpr const char _p11_m11_p12__M10_1_0_M4_1_0_3[] PROGMEM = "<+11>-11<+12>,M10.1.0,M4.1.0/3";
constexpr const char _m08_8[] PROGMEM = "<-08>8";
constexpr const char _m10_10[] PROGMEM = "<-10>10";
constexpr const char _p02_m2[] PROGMEM = "<+02>-2";
constexpr const char _m07_7[] PROGMEM = "<-07>7";
constexpr const char _m12_12[] PROGMEM = "<-12>12";
constexpr const char UTC0[] PROGMEM = "UTC0";


} // namespace data

// timezones mapping table
constexpr const char *timezones[][2] PROGMEM = {
{ data::Africa_Abidjan, data::GMT0 },
{ data::Africa_Accra, data::GMT0 },
{ data::Africa_Addis_Ababa, data::EATm3 },
{ data::Africa_Algiers, data::CETm1 },
{ data::Africa_Asmara, data::EATm3 },
{ data::Africa_Bamako, data::GMT0 },
{ data::Africa_Bangui, data::WATm1 },
{ data::Africa_Banjul, data::GMT0 },
{ data::Africa_Bissau, data::GMT0 },
{ data::Africa_Blantyre, data::CATm2 },
{ data::Africa_Brazzaville, data::WATm1 },
{ data::Africa_Bujumbura, data::CATm2 },
{ data::Africa_Cairo, data::EETm2 },
{ data::Africa_Casablanca, data::_p01_m1 },
{ data::Africa_Ceuta, data::CETm1CEST_M3_5_0_M10_5_0_3 },
{ data::Africa_Conakry, data::GMT0 },
{ data::Africa_Dakar, data::GMT0 },
{ data::Africa_Dar_es_Salaam, data::EATm3 },
{ data::Africa_Djibouti, data::EATm3 },
{ data::Africa_Douala, data::WATm1 },
{ data::Africa_El_Aaiun, data::_p01_m1 },
{ data::Africa_Freetown, data::GMT0 },
{ data::Africa_Gaborone, data::CATm2 },
{ data::Africa_Harare, data::CATm2 },
{ data::Africa_Johannesburg, data::SASTm2 },
{ data::Africa_Juba, data::CATm2 },
{ data::Africa_Kampala, data::EATm3 },
{ data::Africa_Khartoum, data::CATm2 },
{ data::Africa_Kigali, data::CATm2 },
{ data::Africa_Kinshasa, data::WATm1 },
{ data::Africa_Lagos, data::WATm1 },
{ data::Africa_Libreville, data::WATm1 },
{ data::Africa_Lome, data::GMT0 },
{ data::Africa_Luanda, data::WATm1 },
{ data::Africa_Lubumbashi, data::CATm2 },
{ data::Africa_Lusaka, data::CATm2 },
{ data::Africa_Malabo, data::WATm1 },
{ data::Africa_Maputo, data::CATm2 },
{ data::Africa_Maseru, data::SASTm2 },
{ data::Africa_Mbabane, data::SASTm2 },
{ data::Africa_Mogadishu, data::EATm3 },
{ data::Africa_Monrovia, data::GMT0 },
{ data::Africa_Nairobi, data::EATm3 },
{ data::Africa_Ndjamena, data::WATm1 },
{ data::Africa_Niamey, data::WATm1 },
{ data::Africa_Nouakchott, data::GMT0 },
{ data::Africa_Ouagadougou, data::GMT0 },
{ data::Africa_Porto_Novo, data::WATm1 },
{ data::Africa_Sao_Tome, data::GMT0 },
{ data::Africa_Tripoli, data::EETm2 },
{ data::Africa_Tunis, data::CETm1 },
{ data::Africa_Windhoek, data::CATm2 },
{ data::America_Adak, data::HST10HDT_M3_2_0_M11_1_0 },
{ data::America_Anchorage, data::AKST9AKDT_M3_2_0_M11_1_0 },
{ data::America_Anguilla, data::AST4 },
{ data::America_Antigua, data::AST4 },
{ data::America_Araguaina, data::_m03_3 },
{ data::America_Argentina_Buenos_Aires, data::_m03_3 },
{ data::America_Argentina_Catamarca, data::_m03_3 },
{ data::America_Argentina_Cordoba, data::_m03_3 },
{ data::America_Argentina_Jujuy, data::_m03_3 },
{ data::America_Argentina_La_Rioja, data::_m03_3 },
{ data::America_Argentina_Mendoza, data::_m03_3 },
{ data::America_Argentina_Rio_Gallegos, data::_m03_3 },
{ data::America_Argentina_Salta, data::_m03_3 },
{ data::America_Argentina_San_Juan, data::_m03_3 },
{ data::America_Argentina_San_Luis, data::_m03_3 },
{ data::America_Argentina_Tucuman, data::_m03_3 },
{ data::America_Argentina_Ushuaia, data::_m03_3 },
{ data::America_Aruba, data::AST4 },
{ data::America_Asuncion, data::_m04_4_m03__M10_1_0_0_M3_4_0_0 },
{ data::America_Atikokan, data::EST5 },
{ data::America_Bahia, data::_m03_3 },
{ data::America_Bahia_Banderas, data::CST6CDT_M4_1_0_M10_5_0 },
{ data::America_Barbados, data::AST4 },
{ data::America_Belem, data::_m03_3 },
{ data::America_Belize, data::CST6 },
{ data::America_Blanc_Sablon, data::AST4 },
{ data::America_Boa_Vista, data::_m04_4 },
{ data::America_Bogota, data::_m05_5 },
{ data::America_Boise, data::MST7MDT_M3_2_0_M11_1_0 },
{ data::America_Cambridge_Bay, data::MST7MDT_M3_2_0_M11_1_0 },
{ data::America_Campo_Grande, data::_m04_4 },
{ data::America_Cancun, data::EST5 },
{ data::America_Caracas, data::_m04_4 },
{ data::America_Cayenne, data::_m03_3 },
{ data::America_Cayman, data::EST5 },
{ data::America_Chicago, data::CST6CDT_M3_2_0_M11_1_0 },
{ data::America_Chihuahua, data::MST7MDT_M4_1_0_M10_5_0 },
{ data::America_Costa_Rica, data::CST6 },
{ data::America_Creston, data::MST7 },
{ data::America_Cuiaba, data::_m04_4 },
{ data::America_Curacao, data::AST4 },
{ data::America_Danmarkshavn, data::GMT0 },
{ data::America_Dawson, data::MST7 },
{ data::America_Dawson_Creek, data::MST7 },
{ data::America_Denver, data::MST7MDT_M3_2_0_M11_1_0 },
{ data::America_Detroit, data::EST5EDT_M3_2_0_M11_1_0 },
{ data::America_Dominica, data::AST4 },
{ data::America_Edmonton, data::MST7MDT_M3_2_0_M11_1_0 },
{ data::America_Eirunepe, data::_m05_5 },
{ data::America_El_Salvador, data::CST6 },
{ data::America_Fortaleza, data::_m03_3 },
{ data::America_Fort_Nelson, data::MST7 },
{ data::America_Glace_Bay, data::AST4ADT_M3_2_0_M11_1_0 },
{ data::America_Godthab, data::_m03_3_m02__M3_5_0_m2_M10_5_0_m1 },
{ data::America_Goose_Bay, data::AST4ADT_M3_2_0_M11_1_0 },
{ data::America_Grand_Turk, data::EST5EDT_M3_2_0_M11_1_0 },
{ data::America_Grenada, data::AST4 },
{ data::America_Guadeloupe, data::AST4 },
{ data::America_Guatemala, data::CST6 },
{ data::America_Guayaquil, data::_m05_5 },
{ data::America_Guyana, data::_m04_4 },
{ data::America_Halifax, data::AST4ADT_M3_2_0_M11_1_0 },
{ data::America_Havana, data::CST5CDT_M3_2_0_0_M11_1_0_1 },
{ data::America_Hermosillo, data::MST7 },
{ data::America_Indiana_Indianapolis, data::EST5EDT_M3_2_0_M11_1_0 },
{ data::America_Indiana_Knox, data::CST6CDT_M3_2_0_M11_1_0 },
{ data::America_Indiana_Marengo, data::EST5EDT_M3_2_0_M11_1_0 },
{ data::America_Indiana_Petersburg, data::EST5EDT_M3_2_0_M11_1_0 },
{ data::America_Indiana_Tell_City, data::CST6CDT_M3_2_0_M11_1_0 },
{ data::America_Indiana_Vevay, data::EST5EDT_M3_2_0_M11_1_0 },
{ data::America_Indiana_Vincennes, data::EST5EDT_M3_2_0_M11_1_0 },
{ data::America_Indiana_Winamac, data::EST5EDT_M3_2_0_M11_1_0 },
{ data::America_Inuvik, data::MST7MDT_M3_2_0_M11_1_0 },
{ data::America_Iqaluit, data::EST5EDT_M3_2_0_M11_1_0 },
{ data::America_Jamaica, data::EST5 },
{ data::America_Juneau, data::AKST9AKDT_M3_2_0_M11_1_0 },
{ data::America_Kentucky_Louisville, data::EST5EDT_M3_2_0_M11_1_0 },
{ data::America_Kentucky_Monticello, data::EST5EDT_M3_2_0_M11_1_0 },
{ data::America_Kralendijk, data::AST4 },
{ data::America_La_Paz, data::_m04_4 },
{ data::America_Lima, data::_m05_5 },
{ data::America_Los_Angeles, data::PST8PDT_M3_2_0_M11_1_0 },
{ data::America_Lower_Princes, data::AST4 },
{ data::America_Maceio, data::_m03_3 },
{ data::America_Managua, data::CST6 },
{ data::America_Manaus, data::_m04_4 },
{ data::America_Marigot, data::AST4 },
{ data::America_Martinique, data::AST4 },
{ data::America_Matamoros, data::CST6CDT_M3_2_0_M11_1_0 },
{ data::America_Mazatlan, data::MST7MDT_M4_1_0_M10_5_0 },
{ data::America_Menominee, data::CST6CDT_M3_2_0_M11_1_0 },
{ data::America_Merida, data::CST6CDT_M4_1_0_M10_5_0 },
{ data::America_Metlakatla, data::AKST9AKDT_M3_2_0_M11_1_0 },
{ data::America_Mexico_City, data::CST6CDT_M4_1_0_M10_5_0 },
{ data::America_Miquelon, data::_m03_3_m02__M3_2_0_M11_1_0 },
{ data::America_Moncton, data::AST4ADT_M3_2_0_M11_1_0 },
{ data::America_Monterrey, data::CST6CDT_M4_1_0_M10_5_0 },
{ data::America_Montevideo, data::_m03_3 },
{ data::America_Montreal, data::EST5EDT_M3_2_0_M11_1_0 },
{ data::America_Montserrat, data::AST4 },
{ data::America_Nassau, data::EST5EDT_M3_2_0_M11_1_0 },
{ data::America_New_York, data::EST5EDT_M3_2_0_M11_1_0 },
{ data::America_Nipigon, data::EST5EDT_M3_2_0_M11_1_0 },
{ data::America_Nome, data::AKST9AKDT_M3_2_0_M11_1_0 },
{ data::America_Noronha, data::_m02_2 },
{ data::America_North_Dakota_Beulah, data::CST6CDT_M3_2_0_M11_1_0 },
{ data::America_North_Dakota_Center, data::CST6CDT_M3_2_0_M11_1_0 },
{ data::America_North_Dakota_New_Salem, data::CST6CDT_M3_2_0_M11_1_0 },
{ data::America_Nuuk, data::_m03_3_m02__M3_5_0_m2_M10_5_0_m1 },
{ data::America_Ojinaga, data::MST7MDT_M3_2_0_M11_1_0 },
{ data::America_Panama, data::EST5 },
{ data::America_Pangnirtung, data::EST5EDT_M3_2_0_M11_1_0 },
{ data::America_Paramaribo, data::_m03_3 },
{ data::America_Phoenix, data::MST7 },
{ data::America_Port_au_Prince, data::EST5EDT_M3_2_0_M11_1_0 },
{ data::America_Port_of_Spain, data::AST4 },
{ data::America_Porto_Velho, data::_m04_4 },
{ data::America_Puerto_Rico, data::AST4 },
{ data::America_Punta_Arenas, data::_m03_3 },
{ data::America_Rainy_River, data::CST6CDT_M3_2_0_M11_1_0 },
{ data::America_Rankin_Inlet, data::CST6CDT_M3_2_0_M11_1_0 },
{ data::America_Recife, data::_m03_3 },
{ data::America_Regina, data::CST6 },
{ data::America_Resolute, data::CST6CDT_M3_2_0_M11_1_0 },
{ data::America_Rio_Branco, data::_m05_5 },
{ data::America_Santarem, data::_m03_3 },
{ data::America_Santiago, data::_m04_4_m03__M9_1_6_24_M4_1_6_24 },
{ data::America_Santo_Domingo, data::AST4 },
{ data::America_Sao_Paulo, data::_m03_3 },
{ data::America_Scoresbysund, data::_m01_1_p00__M3_5_0_0_M10_5_0_1 },
{ data::America_Sitka, data::AKST9AKDT_M3_2_0_M11_1_0 },
{ data::America_St_Barthelemy, data::AST4 },
{ data::America_St_Johns, data::NST3_30NDT_M3_2_0_M11_1_0 },
{ data::America_St_Kitts, data::AST4 },
{ data::America_St_Lucia, data::AST4 },
{ data::America_St_Thomas, data::AST4 },
{ data::America_St_Vincent, data::AST4 },
{ data::America_Swift_Current, data::CST6 },
{ data::America_Tegucigalpa, data::CST6 },
{ data::America_Thule, data::AST4ADT_M3_2_0_M11_1_0 },
{ data::America_Thunder_Bay, data::EST5EDT_M3_2_0_M11_1_0 },
{ data::America_Tijuana, data::PST8PDT_M3_2_0_M11_1_0 },
{ data::America_Toronto, data::EST5EDT_M3_2_0_M11_1_0 },
{ data::America_Tortola, data::AST4 },
{ data::America_Vancouver, data::PST8PDT_M3_2_0_M11_1_0 },
{ data::America_Whitehorse, data::MST7 },
{ data::America_Winnipeg, data::CST6CDT_M3_2_0_M11_1_0 },
{ data::America_Yakutat, data::AKST9AKDT_M3_2_0_M11_1_0 },
{ data::America_Yellowknife, data::MST7MDT_M3_2_0_M11_1_0 },
{ data::Antarctica_Casey, data::_p11_m11 },
{ data::Antarctica_Davis, data::_p07_m7 },
{ data::Antarctica_DumontDUrville, data::_p10_m10 },
{ data::Antarctica_Macquarie, data::AESTm10AEDT_M10_1_0_M4_1_0_3 },
{ data::Antarctica_Mawson, data::_p05_m5 },
{ data::Antarctica_McMurdo, data::NZSTm12NZDT_M9_5_0_M4_1_0_3 },
{ data::Antarctica_Palmer, data::_m03_3 },
{ data::Antarctica_Rothera, data::_m03_3 },
{ data::Antarctica_Syowa, data::_p03_m3 },
{ data::Antarctica_Troll, data::_p00_0_p02_m2_M3_5_0_1_M10_5_0_3 },
{ data::Antarctica_Vostok, data::_p06_m6 },
{ data::Arctic_Longyearbyen, data::CETm1CEST_M3_5_0_M10_5_0_3 },
{ data::Asia_Aden, data::_p03_m3 },
{ data::Asia_Almaty, data::_p06_m6 },
{ data::Asia_Amman, data::EETm2EEST_M2_5_4_24_M10_5_5_1 },
{ data::Asia_Anadyr, data::_p12_m12 },
{ data::Asia_Aqtau, data::_p05_m5 },
{ data::Asia_Aqtobe, data::_p05_m5 },
{ data::Asia_Ashgabat, data::_p05_m5 },
{ data::Asia_Atyrau, data::_p05_m5 },
{ data::Asia_Baghdad, data::_p03_m3 },
{ data::Asia_Bahrain, data::_p03_m3 },
{ data::Asia_Baku, data::_p04_m4 },
{ data::Asia_Bangkok, data::_p07_m7 },
{ data::Asia_Barnaul, data::_p07_m7 },
{ data::Asia_Beirut, data::EETm2EEST_M3_5_0_0_M10_5_0_0 },
{ data::Asia_Bishkek, data::_p06_m6 },
{ data::Asia_Brunei, data::_p08_m8 },
{ data::Asia_Chita, data::_p09_m9 },
{ data::Asia_Choibalsan, data::_p08_m8 },
{ data::Asia_Colombo, data::_p0530_m5_30 },
{ data::Asia_Damascus, data::EETm2EEST_M3_5_5_0_M10_5_5_0 },
{ data::Asia_Dhaka, data::_p06_m6 },
{ data::Asia_Dili, data::_p09_m9 },
{ data::Asia_Dubai, data::_p04_m4 },
{ data::Asia_Dushanbe, data::_p05_m5 },
{ data::Asia_Famagusta, data::EETm2EEST_M3_5_0_3_M10_5_0_4 },
{ data::Asia_Gaza, data::EETm2EEST_M3_4_4_48_M10_5_5_1 },
{ data::Asia_Hebron, data::EETm2EEST_M3_4_4_48_M10_5_5_1 },
{ data::Asia_Ho_Chi_Minh, data::_p07_m7 },
{ data::Asia_Hong_Kong, data::HKTm8 },
{ data::Asia_Hovd, data::_p07_m7 },
{ data::Asia_Irkutsk, data::_p08_m8 },
{ data::Asia_Jakarta, data::WIBm7 },
{ data::Asia_Jayapura, data::WITm9 },
{ data::Asia_Jerusalem, data::ISTm2IDT_M3_4_4_26_M10_5_0 },
{ data::Asia_Kabul, data::_p0430_m4_30 },
{ data::Asia_Kamchatka, data::_p12_m12 },
{ data::Asia_Karachi, data::PKTm5 },
{ data::Asia_Kathmandu, data::_p0545_m5_45 },
{ data::Asia_Khandyga, data::_p09_m9 },
{ data::Asia_Kolkata, data::ISTm5_30 },
{ data::Asia_Krasnoyarsk, data::_p07_m7 },
{ data::Asia_Kuala_Lumpur, data::_p08_m8 },
{ data::Asia_Kuching, data::_p08_m8 },
{ data::Asia_Kuwait, data::_p03_m3 },
{ data::Asia_Macau, data::CSTm8 },
{ data::Asia_Magadan, data::_p11_m11 },
{ data::Asia_Makassar, data::WITAm8 },
{ data::Asia_Manila, data::PSTm8 },
{ data::Asia_Muscat, data::_p04_m4 },
{ data::Asia_Nicosia, data::EETm2EEST_M3_5_0_3_M10_5_0_4 },
{ data::Asia_Novokuznetsk, data::_p07_m7 },
{ data::Asia_Novosibirsk, data::_p07_m7 },
{ data::Asia_Omsk, data::_p06_m6 },
{ data::Asia_Oral, data::_p05_m5 },
{ data::Asia_Phnom_Penh, data::_p07_m7 },
{ data::Asia_Pontianak, data::WIBm7 },
{ data::Asia_Pyongyang, data::KSTm9 },
{ data::Asia_Qatar, data::_p03_m3 },
{ data::Asia_Qyzylorda, data::_p05_m5 },
{ data::Asia_Riyadh, data::_p03_m3 },
{ data::Asia_Sakhalin, data::_p11_m11 },
{ data::Asia_Samarkand, data::_p05_m5 },
{ data::Asia_Seoul, data::KSTm9 },
{ data::Asia_Shanghai, data::CSTm8 },
{ data::Asia_Singapore, data::_p08_m8 },
{ data::Asia_Srednekolymsk, data::_p11_m11 },
{ data::Asia_Taipei, data::CSTm8 },
{ data::Asia_Tashkent, data::_p05_m5 },
{ data::Asia_Tbilisi, data::_p04_m4 },
{ data::Asia_Tehran, data::_p0330_m3_30_p0430__J79_24_J263_24 },
{ data::Asia_Thimphu, data::_p06_m6 },
{ data::Asia_Tokyo, data::JSTm9 },
{ data::Asia_Tomsk, data::_p07_m7 },
{ data::Asia_Ulaanbaatar, data::_p08_m8 },
{ data::Asia_Urumqi, data::_p06_m6 },
{ data::Asia_Ust_Nera, data::_p10_m10 },
{ data::Asia_Vientiane, data::_p07_m7 },
{ data::Asia_Vladivostok, data::_p10_m10 },
{ data::Asia_Yakutsk, data::_p09_m9 },
{ data::Asia_Yangon, data::_p0630_m6_30 },
{ data::Asia_Yekaterinburg, data::_p05_m5 },
{ data::Asia_Yerevan, data::_p04_m4 },
{ data::Atlantic_Azores, data::_m01_1_p00__M3_5_0_0_M10_5_0_1 },
{ data::Atlantic_Bermuda, data::AST4ADT_M3_2_0_M11_1_0 },
{ data::Atlantic_Canary, data::WET0WEST_M3_5_0_1_M10_5_0 },
{ data::Atlantic_Cape_Verde, data::_m01_1 },
{ data::Atlantic_Faroe, data::WET0WEST_M3_5_0_1_M10_5_0 },
{ data::Atlantic_Madeira, data::WET0WEST_M3_5_0_1_M10_5_0 },
{ data::Atlantic_Reykjavik, data::GMT0 },
{ data::Atlantic_South_Georgia, data::_m02_2 },
{ data::Atlantic_Stanley, data::_m03_3 },
{ data::Atlantic_St_Helena, data::GMT0 },
{ data::Australia_Adelaide, data::ACSTm9_30ACDT_M10_1_0_M4_1_0_3 },
{ data::Australia_Brisbane, data::AESTm10 },
{ data::Australia_Broken_Hill, data::ACSTm9_30ACDT_M10_1_0_M4_1_0_3 },
{ data::Australia_Currie, data::AESTm10AEDT_M10_1_0_M4_1_0_3 },
{ data::Australia_Darwin, data::ACSTm9_30 },
{ data::Australia_Eucla, data::_p0845_m8_45 },
{ data::Australia_Hobart, data::AESTm10AEDT_M10_1_0_M4_1_0_3 },
{ data::Australia_Lindeman, data::AESTm10 },
{ data::Australia_Lord_Howe, data::_p1030_m10_30_p11_m11_M10_1_0_M4_1_0 },
{ data::Australia_Melbourne, data::AESTm10AEDT_M10_1_0_M4_1_0_3 },
{ data::Australia_Perth, data::AWSTm8 },
{ data::Australia_Sydney, data::AESTm10AEDT_M10_1_0_M4_1_0_3 },
{ data::Europe_Amsterdam, data::CETm1CEST_M3_5_0_M10_5_0_3 },
{ data::Europe_Andorra, data::CETm1CEST_M3_5_0_M10_5_0_3 },
{ data::Europe_Astrakhan, data::_p04_m4 },
{ data::Europe_Athens, data::EETm2EEST_M3_5_0_3_M10_5_0_4 },
{ data::Europe_Belgrade, data::CETm1CEST_M3_5_0_M10_5_0_3 },
{ data::Europe_Berlin, data::CETm1CEST_M3_5_0_M10_5_0_3 },
{ data::Europe_Bratislava, data::CETm1CEST_M3_5_0_M10_5_0_3 },
{ data::Europe_Brussels, data::CETm1CEST_M3_5_0_M10_5_0_3 },
{ data::Europe_Bucharest, data::EETm2EEST_M3_5_0_3_M10_5_0_4 },
{ data::Europe_Budapest, data::CETm1CEST_M3_5_0_M10_5_0_3 },
{ data::Europe_Busingen, data::CETm1CEST_M3_5_0_M10_5_0_3 },
{ data::Europe_Chisinau, data::EETm2EEST_M3_5_0_M10_5_0_3 },
{ data::Europe_Copenhagen, data::CETm1CEST_M3_5_0_M10_5_0_3 },
{ data::Europe_Dublin, data::ISTm1GMT0_M10_5_0_M3_5_0_1 },
{ data::Europe_Gibraltar, data::CETm1CEST_M3_5_0_M10_5_0_3 },
{ data::Europe_Guernsey, data::GMT0BST_M3_5_0_1_M10_5_0 },
{ data::Europe_Helsinki, data::EETm2EEST_M3_5_0_3_M10_5_0_4 },
{ data::Europe_Isle_of_Man, data::GMT0BST_M3_5_0_1_M10_5_0 },
{ data::Europe_Istanbul, data::_p03_m3 },
{ data::Europe_Jersey, data::GMT0BST_M3_5_0_1_M10_5_0 },
{ data::Europe_Kaliningrad, data::EETm2 },
{ data::Europe_Kiev, data::EETm2EEST_M3_5_0_3_M10_5_0_4 },
{ data::Europe_Kirov, data::_p03_m3 },
{ data::Europe_Lisbon, data::WET0WEST_M3_5_0_1_M10_5_0 },
{ data::Europe_Ljubljana, data::CETm1CEST_M3_5_0_M10_5_0_3 },
{ data::Europe_London, data::GMT0BST_M3_5_0_1_M10_5_0 },
{ data::Europe_Luxembourg, data::CETm1CEST_M3_5_0_M10_5_0_3 },
{ data::Europe_Madrid, data::CETm1CEST_M3_5_0_M10_5_0_3 },
{ data::Europe_Malta, data::CETm1CEST_M3_5_0_M10_5_0_3 },
{ data::Europe_Mariehamn, data::EETm2EEST_M3_5_0_3_M10_5_0_4 },
{ data::Europe_Minsk, data::_p03_m3 },
{ data::Europe_Monaco, data::CETm1CEST_M3_5_0_M10_5_0_3 },
{ data::Europe_Moscow, data::MSKm3 },
{ data::Europe_Oslo, data::CETm1CEST_M3_5_0_M10_5_0_3 },
{ data::Europe_Paris, data::CETm1CEST_M3_5_0_M10_5_0_3 },
{ data::Europe_Podgorica, data::CETm1CEST_M3_5_0_M10_5_0_3 },
{ data::Europe_Prague, data::CETm1CEST_M3_5_0_M10_5_0_3 },
{ data::Europe_Riga, data::EETm2EEST_M3_5_0_3_M10_5_0_4 },
{ data::Europe_Rome, data::CETm1CEST_M3_5_0_M10_5_0_3 },
{ data::Europe_Samara, data::_p04_m4 },
{ data::Europe_San_Marino, data::CETm1CEST_M3_5_0_M10_5_0_3 },
{ data::Europe_Sarajevo, data::CETm1CEST_M3_5_0_M10_5_0_3 },
{ data::Europe_Saratov, data::_p04_m4 },
{ data::Europe_Simferopol, data::MSKm3 },
{ data::Europe_Skopje, data::CETm1CEST_M3_5_0_M10_5_0_3 },
{ data::Europe_Sofia, data::EETm2EEST_M3_5_0_3_M10_5_0_4 },
{ data::Europe_Stockholm, data::CETm1CEST_M3_5_0_M10_5_0_3 },
{ data::Europe_Tallinn, data::EETm2EEST_M3_5_0_3_M10_5_0_4 },
{ data::Europe_Tirane, data::CETm1CEST_M3_5_0_M10_5_0_3 },
{ data::Europe_Ulyanovsk, data::_p04_m4 },
{ data::Europe_Uzhgorod, data::EETm2EEST_M3_5_0_3_M10_5_0_4 },
{ data::Europe_Vaduz, data::CETm1CEST_M3_5_0_M10_5_0_3 },
{ data::Europe_Vatican, data::CETm1CEST_M3_5_0_M10_5_0_3 },
{ data::Europe_Vienna, data::CETm1CEST_M3_5_0_M10_5_0_3 },
{ data::Europe_Vilnius, data::EETm2EEST_M3_5_0_3_M10_5_0_4 },
{ data::Europe_Volgograd, data::_p03_m3 },
{ data::Europe_Warsaw, data::CETm1CEST_M3_5_0_M10_5_0_3 },
{ data::Europe_Zagreb, data::CETm1CEST_M3_5_0_M10_5_0_3 },
{ data::Europe_Zaporozhye, data::EETm2EEST_M3_5_0_3_M10_5_0_4 },
{ data::Europe_Zurich, data::CETm1CEST_M3_5_0_M10_5_0_3 },
{ data::Indian_Antananarivo, data::EATm3 },
{ data::Indian_Chagos, data::_p06_m6 },
{ data::Indian_Christmas, data::_p07_m7 },
{ data::Indian_Cocos, data::_p0630_m6_30 },
{ data::Indian_Comoro, data::EATm3 },
{ data::Indian_Kerguelen, data::_p05_m5 },
{ data::Indian_Mahe, data::_p04_m4 },
{ data::Indian_Maldives, data::_p05_m5 },
{ data::Indian_Mauritius, data::_p04_m4 },
{ data::Indian_Mayotte, data::EATm3 },
{ data::Indian_Reunion, data::_p04_m4 },
{ data::Pacific_Apia, data::_p13_m13 },
{ data::Pacific_Auckland, data::NZSTm12NZDT_M9_5_0_M4_1_0_3 },
{ data::Pacific_Bougainville, data::_p11_m11 },
{ data::Pacific_Chatham, data::_p1245_m12_45_p1345__M9_5_0_2_45_M4_1_0_3_45 },
{ data::Pacific_Chuuk, data::_p10_m10 },
{ data::Pacific_Easter, data::_m06_6_m05__M9_1_6_22_M4_1_6_22 },
{ data::Pacific_Efate, data::_p11_m11 },
{ data::Pacific_Enderbury, data::_p13_m13 },
{ data::Pacific_Fakaofo, data::_p13_m13 },
{ data::Pacific_Fiji, data::_p12_m12_p13__M11_2_0_M1_2_3_99 },
{ data::Pacific_Funafuti, data::_p12_m12 },
{ data::Pacific_Galapagos, data::_m06_6 },
{ data::Pacific_Gambier, data::_m09_9 },
{ data::Pacific_Guadalcanal, data::_p11_m11 },
{ data::Pacific_Guam, data::ChSTm10 },
{ data::Pacific_Honolulu, data::HST10 },
{ data::Pacific_Kiritimati, data::_p14_m14 },
{ data::Pacific_Kosrae, data::_p11_m11 },
{ data::Pacific_Kwajalein, data::_p12_m12 },
{ data::Pacific_Majuro, data::_p12_m12 },
{ data::Pacific_Marquesas, data::_m0930_9_30 },
{ data::Pacific_Midway, data::SST11 },
{ data::Pacific_Nauru, data::_p12_m12 },
{ data::Pacific_Niue, data::_m11_11 },
{ data::Pacific_Norfolk, data::_p11_m11_p12__M10_1_0_M4_1_0_3 },
{ data::Pacific_Noumea, data::_p11_m11 },
{ data::Pacific_Pago_Pago, data::SST11 },
{ data::Pacific_Palau, data::_p09_m9 },
{ data::Pacific_Pitcairn, data::_m08_8 },
{ data::Pacific_Pohnpei, data::_p11_m11 },
{ data::Pacific_Port_Moresby, data::_p10_m10 },
{ data::Pacific_Rarotonga, data::_m10_10 },
{ data::Pacific_Saipan, data::ChSTm10 },
{ data::Pacific_Tahiti, data::_m10_10 },
{ data::Pacific_Tarawa, data::_p12_m12 },
{ data::Pacific_Tongatapu, data::_p13_m13 },
{ data::Pacific_Wake, data::_p12_m12 },
{ data::Pacific_Wallis, data::_p12_m12 },
{ data::Etc_GMT, data::GMT0 },
{ data::Etc_GMT_0, data::GMT0 },
{ data::Etc_GMT_1, data::_m01_1 },
{ data::Etc_GMT_2, data::_m02_2 },
{ data::Etc_GMT_3, data::_m03_3 },
{ data::Etc_GMT_4, data::_m04_4 },
{ data::Etc_GMT_5, data::_m05_5 },
{ data::Etc_GMT_6, data::_m06_6 },
{ data::Etc_GMT_7, data::_m07_7 },
{ data::Etc_GMT_8, data::_m08_8 },
{ data::Etc_GMT_9, data::_m09_9 },
{ data::Etc_GMT_10, data::_m10_10 },
{ data::Etc_GMT_11, data::_m11_11 },
{ data::Etc_GMT_12, data::_m12_12 },
{ data::Etc_GMT_13, data::_p13_m13 },
{ data::Etc_GMT_14, data::_p14_m14 },
{ data::Etc_GMT0, data::GMT0 },
{ data::Etc_UCT, data::UTC0 },
{ data::Etc_UTC, data::UTC0 },
{ data::Etc_Greenwich, data::GMT0 },
{ data::Etc_Universal, data::UTC0 },
{ data::Etc_Zulu, data::UTC0 },
};
constexpr size_t timezoneSize = 448;

//timezone enum
enum TZ_Names : size_t {
TZ_Africa_Abidjan = 0,
TZ_Africa_Accra,
TZ_Africa_Addis_Ababa,
TZ_Africa_Algiers,
TZ_Africa_Asmara,
TZ_Africa_Bamako,
TZ_Africa_Bangui,
TZ_Africa_Banjul,
TZ_Africa_Bissau,
TZ_Africa_Blantyre,
TZ_Africa_Brazzaville,
TZ_Africa_Bujumbura,
TZ_Africa_Cairo,
TZ_Africa_Casablanca,
TZ_Africa_Ceuta,
TZ_Africa_Conakry,
TZ_Africa_Dakar,
TZ_Africa_Dar_es_Salaam,
TZ_Africa_Djibouti,
TZ_Africa_Douala,
TZ_Africa_El_Aaiun,
TZ_Africa_Freetown,
TZ_Africa_Gaborone,
TZ_Africa_Harare,
TZ_Africa_Johannesburg,
TZ_Africa_Juba,
TZ_Africa_Kampala,
TZ_Africa_Khartoum,
TZ_Africa_Kigali,
TZ_Africa_Kinshasa,
TZ_Africa_Lagos,
TZ_Africa_Libreville,
TZ_Africa_Lome,
TZ_Africa_Luanda,
TZ_Africa_Lubumbashi,
TZ_Africa_Lusaka,
TZ_Africa_Malabo,
TZ_Africa_Maputo,
TZ_Africa_Maseru,
TZ_Africa_Mbabane,
TZ_Africa_Mogadishu,
TZ_Africa_Monrovia,
TZ_Africa_Nairobi,
TZ_Africa_Ndjamena,
TZ_Africa_Niamey,
TZ_Africa_Nouakchott,
TZ_Africa_Ouagadougou,
TZ_Africa_Porto_Novo,
TZ_Africa_Sao_Tome,
TZ_Africa_Tripoli,
TZ_Africa_Tunis,
TZ_Africa_Windhoek,
TZ_America_Adak,
TZ_America_Anchorage,
TZ_America_Anguilla,
TZ_America_Antigua,
TZ_America_Araguaina,
TZ_America_Argentina_Buenos_Aires,
TZ_America_Argentina_Catamarca,
TZ_America_Argentina_Cordoba,
TZ_America_Argentina_Jujuy,
TZ_America_Argentina_La_Rioja,
TZ_America_Argentina_Mendoza,
TZ_America_Argentina_Rio_Gallegos,
TZ_America_Argentina_Salta,
TZ_America_Argentina_San_Juan,
TZ_America_Argentina_San_Luis,
TZ_America_Argentina_Tucuman,
TZ_America_Argentina_Ushuaia,
TZ_America_Aruba,
TZ_America_Asuncion,
TZ_America_Atikokan,
TZ_America_Bahia,
TZ_America_Bahia_Banderas,
TZ_America_Barbados,
TZ_America_Belem,
TZ_America_Belize,
TZ_America_Blanc_Sablon,
TZ_America_Boa_Vista,
TZ_America_Bogota,
TZ_America_Boise,
TZ_America_Cambridge_Bay,
TZ_America_Campo_Grande,
TZ_America_Cancun,
TZ_America_Caracas,
TZ_America_Cayenne,
TZ_America_Cayman,
TZ_America_Chicago,
TZ_America_Chihuahua,
TZ_America_Costa_Rica,
TZ_America_Creston,
TZ_America_Cuiaba,
TZ_America_Curacao,
TZ_America_Danmarkshavn,
TZ_America_Dawson,
TZ_America_Dawson_Creek,
TZ_America_Denver,
TZ_America_Detroit,
TZ_America_Dominica,
TZ_America_Edmonton,
TZ_America_Eirunepe,
TZ_America_El_Salvador,
TZ_America_Fortaleza,
TZ_America_Fort_Nelson,
TZ_America_Glace_Bay,
TZ_America_Godthab,
TZ_America_Goose_Bay,
TZ_America_Grand_Turk,
TZ_America_Grenada,
TZ_America_Guadeloupe,
TZ_America_Guatemala,
TZ_America_Guayaquil,
TZ_America_Guyana,
TZ_America_Halifax,
TZ_America_Havana,
TZ_America_Hermosillo,
TZ_America_Indiana_Indianapolis,
TZ_America_Indiana_Knox,
TZ_America_Indiana_Marengo,
TZ_America_Indiana_Petersburg,
TZ_America_Indiana_Tell_City,
TZ_America_Indiana_Vevay,
TZ_America_Indiana_Vincennes,
TZ_America_Indiana_Winamac,
TZ_America_Inuvik,
TZ_America_Iqaluit,
TZ_America_Jamaica,
TZ_America_Juneau,
TZ_America_Kentucky_Louisville,
TZ_America_Kentucky_Monticello,
TZ_America_Kralendijk,
TZ_America_La_Paz,
TZ_America_Lima,
TZ_America_Los_Angeles,
TZ_America_Lower_Princes,
TZ_America_Maceio,
TZ_America_Managua,
TZ_America_Manaus,
TZ_America_Marigot,
TZ_America_Martinique,
TZ_America_Matamoros,
TZ_America_Mazatlan,
TZ_America_Menominee,
TZ_America_Merida,
TZ_America_Metlakatla,
TZ_America_Mexico_City,
TZ_America_Miquelon,
TZ_America_Moncton,
TZ_America_Monterrey,
TZ_America_Montevideo,
TZ_America_Montreal,
TZ_America_Montserrat,
TZ_America_Nassau,
TZ_America_New_York,
TZ_America_Nipigon,
TZ_America_Nome,
TZ_America_Noronha,
TZ_America_North_Dakota_Beulah,
TZ_America_North_Dakota_Center,
TZ_America_North_Dakota_New_Salem,
TZ_America_Nuuk,
TZ_America_Ojinaga,
TZ_America_Panama,
TZ_America_Pangnirtung,
TZ_America_Paramaribo,
TZ_America_Phoenix,
TZ_America_Port_au_Prince,
TZ_America_Port_of_Spain,
TZ_America_Porto_Velho,
TZ_America_Puerto_Rico,
TZ_America_Punta_Arenas,
TZ_America_Rainy_River,
TZ_America_Rankin_Inlet,
TZ_America_Recife,
TZ_America_Regina,
TZ_America_Resolute,
TZ_America_Rio_Branco,
TZ_America_Santarem,
TZ_America_Santiago,
TZ_America_Santo_Domingo,
TZ_America_Sao_Paulo,
TZ_America_Scoresbysund,
TZ_America_Sitka,
TZ_America_St_Barthelemy,
TZ_America_St_Johns,
TZ_America_St_Kitts,
TZ_America_St_Lucia,
TZ_America_St_Thomas,
TZ_America_St_Vincent,
TZ_America_Swift_Current,
TZ_America_Tegucigalpa,
TZ_America_Thule,
TZ_America_Thunder_Bay,
TZ_America_Tijuana,
TZ_America_Toronto,
TZ_America_Tortola,
TZ_America_Vancouver,
TZ_America_Whitehorse,
TZ_America_Winnipeg,
TZ_America_Yakutat,
TZ_America_Yellowknife,
TZ_Antarctica_Casey,
TZ_Antarctica_Davis,
TZ_Antarctica_DumontDUrville,
TZ_Antarctica_Macquarie,
TZ_Antarctica_Mawson,
TZ_Antarctica_McMurdo,
TZ_Antarctica_Palmer,
TZ_Antarctica_Rothera,
TZ_Antarctica_Syowa,
TZ_Antarctica_Troll,
TZ_Antarctica_Vostok,
TZ_Arctic_Longyearbyen,
TZ_Asia_Aden,
TZ_Asia_Almaty,
TZ_Asia_Amman,
TZ_Asia_Anadyr,
TZ_Asia_Aqtau,
TZ_Asia_Aqtobe,
TZ_Asia_Ashgabat,
TZ_Asia_Atyrau,
TZ_Asia_Baghdad,
TZ_Asia_Bahrain,
TZ_Asia_Baku,
TZ_Asia_Bangkok,
TZ_Asia_Barnaul,
TZ_Asia_Beirut,
TZ_Asia_Bishkek,
TZ_Asia_Brunei,
TZ_Asia_Chita,
TZ_Asia_Choibalsan,
TZ_Asia_Colombo,
TZ_Asia_Damascus,
TZ_Asia_Dhaka,
TZ_Asia_Dili,
TZ_Asia_Dubai,
TZ_Asia_Dushanbe,
TZ_Asia_Famagusta,
TZ_Asia_Gaza,
TZ_Asia_Hebron,
TZ_Asia_Ho_Chi_Minh,
TZ_Asia_Hong_Kong,
TZ_Asia_Hovd,
TZ_Asia_Irkutsk,
TZ_Asia_Jakarta,
TZ_Asia_Jayapura,
TZ_Asia_Jerusalem,
TZ_Asia_Kabul,
TZ_Asia_Kamchatka,
TZ_Asia_Karachi,
TZ_Asia_Kathmandu,
TZ_Asia_Khandyga,
TZ_Asia_Kolkata,
TZ_Asia_Krasnoyarsk,
TZ_Asia_Kuala_Lumpur,
TZ_Asia_Kuching,
TZ_Asia_Kuwait,
TZ_Asia_Macau,
TZ_Asia_Magadan,
TZ_Asia_Makassar,
TZ_Asia_Manila,
TZ_Asia_Muscat,
TZ_Asia_Nicosia,
TZ_Asia_Novokuznetsk,
TZ_Asia_Novosibirsk,
TZ_Asia_Omsk,
TZ_Asia_Oral,
TZ_Asia_Phnom_Penh,
TZ_Asia_Pontianak,
TZ_Asia_Pyongyang,
TZ_Asia_Qatar,
TZ_Asia_Qyzylorda,
TZ_Asia_Riyadh,
TZ_Asia_Sakhalin,
TZ_Asia_Samarkand,
TZ_Asia_Seoul,
TZ_Asia_Shanghai,
TZ_Asia_Singapore,
TZ_Asia_Srednekolymsk,
TZ_Asia_Taipei,
TZ_Asia_Tashkent,
TZ_Asia_Tbilisi,
TZ_Asia_Tehran,
TZ_Asia_Thimphu,
TZ_Asia_Tokyo,
TZ_Asia_Tomsk,
TZ_Asia_Ulaanbaatar,
TZ_Asia_Urumqi,
TZ_Asia_Ust_Nera,
TZ_Asia_Vientiane,
TZ_Asia_Vladivostok,
TZ_Asia_Yakutsk,
TZ_Asia_Yangon,
TZ_Asia_Yekaterinburg,
TZ_Asia_Yerevan,
TZ_Atlantic_Azores,
TZ_Atlantic_Bermuda,
TZ_Atlantic_Canary,
TZ_Atlantic_Cape_Verde,
TZ_Atlantic_Faroe,
TZ_Atlantic_Madeira,
TZ_Atlantic_Reykjavik,
TZ_Atlantic_South_Georgia,
TZ_Atlantic_Stanley,
TZ_Atlantic_St_Helena,
TZ_Australia_Adelaide,
TZ_Australia_Brisbane,
TZ_Australia_Broken_Hill,
TZ_Australia_Currie,
TZ_Australia_Darwin,
TZ_Australia_Eucla,
TZ_Australia_Hobart,
TZ_Australia_Lindeman,
TZ_Australia_Lord_Howe,
TZ_Australia_Melbourne,
TZ_Australia_Perth,
TZ_Australia_Sydney,
TZ_Europe_Amsterdam,
TZ_Europe_Andorra,
TZ_Europe_Astrakhan,
TZ_Europe_Athens,
TZ_Europe_Belgrade,
TZ_Europe_Berlin,
TZ_Europe_Bratislava,
TZ_Europe_Brussels,
TZ_Europe_Bucharest,
TZ_Europe_Budapest,
TZ_Europe_Busingen,
TZ_Europe_Chisinau,
TZ_Europe_Copenhagen,
TZ_Europe_Dublin,
TZ_Europe_Gibraltar,
TZ_Europe_Guernsey,
TZ_Europe_Helsinki,
TZ_Europe_Isle_of_Man,
TZ_Europe_Istanbul,
TZ_Europe_Jersey,
TZ_Europe_Kaliningrad,
TZ_Europe_Kiev,
TZ_Europe_Kirov,
TZ_Europe_Lisbon,
TZ_Europe_Ljubljana,
TZ_Europe_London,
TZ_Europe_Luxembourg,
TZ_Europe_Madrid,
TZ_Europe_Malta,
TZ_Europe_Mariehamn,
TZ_Europe_Minsk,
TZ_Europe_Monaco,
TZ_Europe_Moscow,
TZ_Europe_Oslo,
TZ_Europe_Paris,
TZ_Europe_Podgorica,
TZ_Europe_Prague,
TZ_Europe_Riga,
TZ_Europe_Rome,
TZ_Europe_Samara,
TZ_Europe_San_Marino,
TZ_Europe_Sarajevo,
TZ_Europe_Saratov,
TZ_Europe_Simferopol,
TZ_Europe_Skopje,
TZ_Europe_Sofia,
TZ_Europe_Stockholm,
TZ_Europe_Tallinn,
TZ_Europe_Tirane,
TZ_Europe_Ulyanovsk,
TZ_Europe_Uzhgorod,
TZ_Europe_Vaduz,
TZ_Europe_Vatican,
TZ_Europe_Vienna,
TZ_Europe_Vilnius,
TZ_Europe_Volgograd,
TZ_Europe_Warsaw,
TZ_Europe_Zagreb,
TZ_Europe_Zaporozhye,
TZ_Europe_Zurich,
TZ_Indian_Antananarivo,
TZ_Indian_Chagos,
TZ_Indian_Christmas,
TZ_Indian_Cocos,
TZ_Indian_Comoro,
TZ_Indian_Kerguelen,
TZ_Indian_Mahe,
TZ_Indian_Maldives,
TZ_Indian_Mauritius,
TZ_Indian_Mayotte,
TZ_Indian_Reunion,
TZ_Pacific_Apia,
TZ_Pacific_Auckland,
TZ_Pacific_Bougainville,
TZ_Pacific_Chatham,
TZ_Pacific_Chuuk,
TZ_Pacific_Easter,
TZ_Pacific_Efate,
TZ_Pacific_Enderbury,
TZ_Pacific_Fakaofo,
TZ_Pacific_Fiji,
TZ_Pacific_Funafuti,
TZ_Pacific_Galapagos,
TZ_Pacific_Gambier,
TZ_Pacific_Guadalcanal,
TZ_Pacific_Guam,
TZ_Pacific_Honolulu,
TZ_Pacific_Kiritimati,
TZ_Pacific_Kosrae,
TZ_Pacific_Kwajalein,
TZ_Pacific_Majuro,
TZ_Pacific_Marquesas,
TZ_Pacific_Midway,
TZ_Pacific_Nauru,
TZ_Pacific_Niue,
TZ_Pacific_Norfolk,
TZ_Pacific_Noumea,
TZ_Pacific_Pago_Pago,
TZ_Pacific_Palau,
TZ_Pacific_Pitcairn,
TZ_Pacific_Pohnpei,
TZ_Pacific_Port_Moresby,
TZ_Pacific_Rarotonga,
TZ_Pacific_Saipan,
TZ_Pacific_Tahiti,
TZ_Pacific_Tarawa,
TZ_Pacific_Tongatapu,
TZ_Pacific_Wake,
TZ_Pacific_Wallis,
TZ_Etc_GMT,
TZ_Etc_GMT_0,
TZ_Etc_GMT_1,
TZ_Etc_GMT_2,
TZ_Etc_GMT_3,
TZ_Etc_GMT_4,
TZ_Etc_GMT_5,
TZ_Etc_GMT_6,
TZ_Etc_GMT_7,
TZ_Etc_GMT_8,
TZ_Etc_GMT_9,
TZ_Etc_GMT_10,
TZ_Etc_GMT_11,
TZ_Etc_GMT_12,
TZ_Etc_GMT_13,
TZ_Etc_GMT_14,
TZ_Etc_GMT0,
TZ_Etc_UCT,
TZ_Etc_UTC,
TZ_Etc_Greenwich,
TZ_Etc_Universal,
TZ_Etc_Zulu,
};